/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-primary": "#abc7ff",
        "tertiary": "#3c1e00",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#d7e2ff",
        "tertiary-container": "#5b3000",
        "on-secondary": "#ffffff",
        "secondary": "#0d50d5",
        "tertiary-fixed": "#ffdcc1",
        "secondary-fixed-dim": "#b5c4ff",
        "secondary-container": "#386bef",
        "primary-fixed-dim": "#abc7ff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-container": "#89a5dd",
        "on-primary-fixed": "#001b3f",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#d7985f",
        "primary-container": "#1a3a6b",
        "error": "#ba1a1a",
        "on-surface": "#191c1e",
        "surface-tint": "#415e91",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#693c0a",
        "on-primary-fixed-variant": "#284678",
        "on-secondary-fixed": "#00174d",
        "on-background": "#191c1e",
        "secondary-fixed": "#dbe1ff",
        "inverse-surface": "#2d3133",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "primary": "#002451",
        "on-error": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed-variant": "#003dab",
        "on-surface-variant": "#43474f",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#fcb87d",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed": "#2e1500",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c4c6d0",
        "surface-dim": "#d8dadc",
        "outline": "#747780",
      },
      fontFamily: {
        "manrope": ["Manrope", "sans-serif"],
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
